name: My fourth Workflow
on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Install cowsay
        run: sudo apt-get update && sudo apt-get install cowsay -y


      - name: Generate ASCII dragon
        run: cowsay -f dragon "Run for cover, I am a DRAGON.... RAWR" >> dragon.txt


      - name: Upload Dragont text file
        uses: actions/upload-artifact@v4.6.2
        with:
          name: dragon-text-fie
          path: dragon.txt


  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download Dragon txt file
        uses: actions/download-artifact@v4.6.2
        with:
          name: dragon-text-file

      - name: Verify dragon.txt
        run: grep -i "dragon" dragon.txt


  deploy_job_3:
    runs-on: ubuntu-latest
    steps:
      - name: Download Dragon txt file
        uses: actions/download-artifact@v4.6.2
        with:
          name: dragon-text-file
s
      - name: Display dragon.txt
        run: cat dragon.txt


      - name: Simulate deployment
        run: echo "Deploying dragon.txt..."